
---
title: "Stock"
author: "Dustin Poon "
---
#Form Christian Kincaid

```{r}
library(quantmod)
library(PerformanceAnalytics)
library(dygraphs)
```

```{r}
#quantmod
monthly_returns <- function(ticker, base_year)
{
  # Obtain stock price data from Yahoo! Finance
  stock <- getSymbols(ticker, src = "yahoo", auto.assign = FALSE) 
  # Remove missing values
  stock <- na.omit(stock)
  # Keep only adjusted closing stock prices
  stock <- stock[, 6]
  
  # Confine our observations to begin at the base year and end at the last available trading day
  horizon <- paste0(as.character(base_year), "/", as.character(Sys.Date()))
  stock <- stock[horizon]
  
  # Calculate monthly arithmetic returns
  data <- periodReturn(stock, period = "monthly", type = "arithmetic")
  
  # Assign to the global environment to be accessible
  assign(ticker, data, envir = .GlobalEnv)
}
```

# visualizing returns

```{r}
monthly_returns("FTS.TO", 2015)
monthly_returns("CU.TO", 2015)
monthly_returns("BCE.TO", 2015)
monthly_returns("GXE.TO", 2015)

# Merge all the data and rename columns
returns <- merge.xts(FTS.TO, CU.TO, BCE.TO, GXE.TO)
colnames(returns) <- c("FTS.TO", "CU.TO", "BCE.TO", "GXE.TO")

# Produce interactive chart of stock returns
dygraph(returns, main = "TITLE") %>%
  dyAxis("y", label = "Return", valueRange = c(-1,0.5)) %>%
  dyRangeSelector(dateWindow = c("2015-01-01", "2023-07-01")) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(4, "Set2")) 

# Print last 5 rows of the data, rounded to 4 decimal places
round(tail(returns, n = 5), 4)
```

Plotting monthly returns for our three stocks and the S&P 500
A fundamental principle of portfolio management is that you should select stocks with low correlations to each other.
```{r}

corrplot::corrplot(cor(returns), method = 'number')
```

```{r}
# Assign weights
wts <- c(1/3, 1/3, 1/3)

#select profolite
portfolio_returns <- Return.portfolio(R = returns[,1:3], weights = wts, wealth.index = TRUE)

# Select bench mark stock
benchmark_returns <- Return.portfolio(R = returns[,4], wealth.index = TRUE)

# Merge the two
comp <- merge.xts(portfolio_returns, benchmark_returns)
colnames(comp) <- c("Portfolio", "Benchmark")

# Build an interactive graph to compare performance
dygraph(comp, main = "Portfolio Performance vs. Benchmark") %>%
  dyAxis("y", label = "Amount ($)")
```

